server:
  port: 8081

spring:
  application:
    name: user-service

# Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

# Info endpoint
info:
  app:
    name: User Service
    description: Handles auth, users, roles
    version: 1.0.0