server:
<<<<<<< HEAD
  port: 8080
=======
  port: ${SERVER_PORT:8080}
>>>>>>> main

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**,/api/users/**
            
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**

            - id: media-service
              uri: lb://media-service
              predicates:
                - Path=/api/media/**

jwt:
<<<<<<< HEAD
  secret: 4fd8a6c3b92f4a8c9c6b8a1f2e3d4c5f6a7b8c9d
=======
  secret: ${JWT_SECRET:4fd8a6c3b92f4a8c9c6b8a1f2e3d4c5f6a7b8c9d}
>>>>>>> main

eureka:
  client:
    service-url:
<<<<<<< HEAD
      defaultZone: http://localhost:8761/eureka/
=======
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
>>>>>>> main
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      access: read-only
  endpoints:
    web:
      exposure:
<<<<<<< HEAD
        include: health,info,gateway
=======
        include: health,info,gateway
>>>>>>> main
